site_name: TIEMS User Guides
site_url: 'https://tiems.co.za'
copyright: <b><a href="https://mapstore.geosolutionsgroup.com" target="_blank">MapStore&copy;</a></b> is Free and Open Source software and is licensed under the Simplified BSD License.
use_directory_urls: true
theme:
  name: 'material'
  highlightjs: true
  icon:
    logo: 'img/mapstore2-logo.png'
    repo: 'fontawesome/brands/github-alt'
    #previous: fontawesome/solid/angle-left
    #next: fontawesome/solid/angle-right
  favicon: 'img/favicon.ico'
  custom_dir: 'docs/theme'
  language: 'en'
  features:
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - search.suggest
    - search.highlight

  logo: 'img/mapstore2-logo.png'
  company_url: 'https://tiems.co.za'
  company_logo: 'img/geosolutions-brand.png'
  company_contacts: 'Tiems Consulting | mlend@outlook.com'
  palette:
    # Dark Mode - mike added
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: dark blue

    # Light mode - mike added
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: dark blue
#    primary: 'teal'
#    accent: 'teal'
# extra:
#   repo_icon: 'github'
#   social:
#     - type: 'github'
#       icon: 'fontawesome/brands/github'
#       link: 'https://github.com/geosolutions-it'
#     - type: 'twitter'
#       icon: 'fontawesome/brands/x-twitter'
#       link: 'https://twitter.com/geosolutions_it'
#     - type: 'linkedin'
#       icon: 'fontawesome/brands/linkedin'
#       link: 'https://it.linkedin.com/company/geosolutions-s-a-s-'
extra_javascript:
  - 'https://code.jquery.com/jquery-3.3.1.min.js'
  - 'https://unpkg.com/mermaid@10.6.0/dist/mermaid.min.js'
extra_css:
  - 'theme/css/extra.css'
# repo_name: 'geosolutions-it/MapStore2'
# repo_url: 'https://github.com/geosolutions-it/MapStore2/'
edit_uri: ''
docs_dir: 'docs'
markdown_extensions:
  - admonition
  - markdown.extensions.attr_list
  - codehilite:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
nav:
  - Home:
      - Home: 'index.md' # To include in pdf
  - TIEMS Map Portal:
      - Home Page Overview: 'map-portal/home-page.md'
      - Managing Users and Groups:
          - Overview: 'map-portal/managing-users-and-groups.md'
          - Managing Users: 'map-portal/managing-users.md'
          - Managing Groups: 'map-portal/managing-groups.md'
      - Managing Contexts:
          - Overview: 'map-portal/managing-contexts.md'
          - Application Context: 'map-portal/application-context.md'
          - Extension Library: 'map-portal/extension-library.md'
          - Map Catalog: 'map-portal/map-catalog.md'
          - Map Templates: 'map-portal/map-templates.md'
      - Resources Properties: 'map-portal/resources-properties.md'
      - Sharing Resources: 'map-portal/share.md'
      - Exploring Maps:
          - Overview: 'map-portal/exploring-maps.md'
          - Table of Contents: 'map-portal/toc.md'
          - Managing Layer Settings: 'map-portal/layer-settings.md'
          - Filtering Layers: 'map-portal/filtering-layers.md'
          - Attribute Table: 'map-portal/attributes-table.md'
          - Widgets: 'map-portal/widgets.md'
          - Export Layer Data: 'map-portal/export-data.md'
          - MapStore Toolbars: 'map-portal/mapstore-toolbars.md'
          - Printing a Map: 'map-portal/print.md'
          - Importing and Exporting Files: 'map-portal/import.md'
          - Catalog Services: 'map-portal/catalog.md'
          - Performing Measurments: 'map-portal/measure.md'
          - Annotations: 'map-portal/annotations.md'
          - Map Views: 'map-portal/map-views.md'
          - Street View: 'map-portal/street-view.md'
          - Longitudinal Profile: 'map-portal/longitudinal-profile.md'
          - GeoProcessing Tool: 'map-portal/geoprocessing-tool.md'
          - Navigation Toolbar: 'map-portal/navigation-toolbar.md'
          - Background Selector: 'map-portal/background.md'
          - Timeline: 'map-portal/timeline.md'
          - Footer: 'map-portal/footer.md'
      - Exploring Dashboards:
          - Overview: 'map-portal/exploring-dashboards.md'
          - Adding widgets: 'map-portal/adding-widgets.md'
          - Connecting widgets: 'map-portal/connecting-widgets.md'
      - Exploring Stories:
          - Overview: 'map-portal/exploring-stories.md'
          - Story Settings: 'map-portal/story-setting.md'
          - Title Section: 'map-portal/title-section.md'
          - Banner Section: 'map-portal/banner-section.md'
          - Paragraph Section: 'map-portal/paragraph-section.md'
          - Immersive Section: 'map-portal/immersive-section.md'
          - GeoCarousel Section: 'map-portal/geocarousel-section.md'
          - Media Section: 'map-portal/media-section.md'
          - Web Page section: 'map-portal/web-section.md'
          - Text Editor Toolbar: 'map-portal/text-editor-toolbar.md'
          - Image Toolbar: 'map-portal/content-image-toolbar.md'
          - Video Toolbar: 'map-portal/content-video-toolbar.md'
          - Map Toolbar: 'map-portal/content-map-toolbar.md'
          - Web Page Toolbar: 'map-portal/content-web-toolbar.md'
          - Media Editor: 'map-portal/media-editor-window.md'
          - Configure the map: 'map-portal/configure-map.md'
  - TIEMS File Hub:
      - Introduction: 'file-hub/introduction.md'
  - Civil Collector App:
      - Introduction: 'civil-collector-app/introduction.md'
  - Maintenance App:
      - Introduction: 'maintenance-app/introduction.md'
  - Building Control App:
      - Introduction: 'building-control-app/introduction.md'

plugins:
  - search
  - with-pdf:
      author: Tiems Consulting
      copyright: 'Tiems'
      #
      #cover: false
      #back_cover: true
      cover_logo: 'img/mapstore2-logo.png'
      cover_title: MapStore Documentation
      cover_subtitle: User Guide and Developer Guide
      toc_level: 3
      output_path: pdf/mapstore_documentation.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      debug_html: true
      show_anchors: true
      verbose: true
